### ISSUE TITLE
TFE cluster not becoming ready

### ISSUE THREAD

**Issue by mohsinrz** [hashicorp/terraform-azurerm-terraform-enterprise#72]
I'm trying to deploy a basic cluster without external services. Dashboard becomes ready but the status remains in starting state and on the primary node I'm getting below errors in logs which shows the other nodes are not able to join the main node but can't figure out what is causing this issue.

```
Jan 22 17:10:11 tfelab-f32svlk5-primary-0 ptfe[28236]: 2020-01-22T17:10:11.415Z [ERROR] Error running node-join-script: err="exit status 1"
Jan 22 17:10:11 tfelab-f32svlk5-primary-0 ptfe[28236]: node-join-script error output:
Jan 22 17:10:11 tfelab-f32svlk5-primary-0 ptfe[28236]: Error: response from daemon: The cluster has reached the maximum number of hosts allowed of 1
Jan 22 17:10:11 tfelab-f32svlk5-primary-0 ptfe[28236]: command terminated with exit code 1

```

**Comment by bnferguson** [comment]
Oh no! Sorry that you ran into this. This happens when the license doesn't have clustering enabled. All licenses _should_ have it enabled so this is a bug with the particular license. Contact support @ support@hashicorp.com or via https://support.hashicorp.com and they should be able to go in to your account and see what's going on with the license.

**Comment by mohsinrz** [comment]
> Oh no! Sorry that you ran into this. This happens when the license doesn't have clustering enabled. All licenses _should_ have it enabled so this is a bug with the particular license. Contact support @ [support@hashicorp.com](mailto:support@hashicorp.com) or via https://support.hashicorp.com and they should be able to go in to your account and see what's going on with the license.

Thanks
