### ISSUE TITLE
License fails to download due to ordering/timing

### ISSUE THREAD

**Issue by josh-barker** [hashicorp/terraform-azurerm-terraform-enterprise#92]
Hi,

I've used the `active_active` example and found that [retrieving](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/blob/master/modules/user_data/templates/tfe.sh.tpl#L104) the license can fail because cloud init starts before the role assignment is created to download the license file.

**Comment by aaron-lane** [comment]
Hi @josh-barker! Thank you for reporting this issue and proposing the fix in #93. Since the cause of the issue is a race condition between resources, I have opened #94 as an alternative solution that utilizes an explicit identity resource for the virtual machine scale set and should fix this issue. Would you like to try testing that solution?

**Comment by josh-barker** [comment]
Hey @aaron-lane, I hadn't considered using a user identity to change the dependency of resources; such a good idea!
I've tested your branch and the it worked correctly.

Thanks for such a quick response and PR! :-)
